# Generated by Django 5.2 on 2025-07-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can view details of books'), ('can_create', 'can create books'), ('can_edit', 'can edit books'), ('can_delete', 'can delete books')]},
        ),
    ]
