# Generated by Django 5.2 on 2025-07-09 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_title'),
    ]

    operations = [
    ]
