# Generated by Django 5.2 on 2025-07-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_auto_20250709_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='publication_year',
        ),
    ]
